// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<'dark' | 'light' | 'system'>;
  onUpdated: (callback: (isDark: boolean) => void) => () => void;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface DockerContext {
  getStatus: () => Promise<{ isRunning: boolean; error?: string }>;
  getNetworkName: () => Promise<string>;
  ensureNetwork: () => Promise<void>;
  connectToNetwork: (containerIdOrName: string) => Promise<void>;
  disconnectFromNetwork: (containerIdOrName: string) => Promise<void>;
}

interface ServicesContext {
  getAllServices: () => Promise<unknown>;
  getService: (serviceId: string) => Promise<unknown>;
  installService: (serviceId: string, options?: unknown) => Promise<unknown>;
  uninstallService: (serviceId: string, removeVolumes?: boolean) => Promise<unknown>;
  startService: (serviceId: string) => Promise<unknown>;
  stopService: (serviceId: string) => Promise<unknown>;
  restartService: (serviceId: string) => Promise<unknown>;
  updateConfig: (serviceId: string, customConfig: unknown) => Promise<unknown>;
  downloadCaddyCertificate: () => Promise<unknown>;
  onInstallProgress: (callback: (serviceId: string, progress: unknown) => void) => () => void;
}

interface ProjectsContext {
  getAllProjects: () => Promise<unknown>;
  getProject: (projectId: string) => Promise<unknown>;
  createProject: (input: unknown) => Promise<unknown>;
  updateProject: (input: unknown) => Promise<unknown>;
  deleteProject: (
    projectId: string,
    removeVolume?: boolean,
    removeFolder?: boolean
  ) => Promise<unknown>;
  reorderProjects: (projectIds: string[]) => Promise<unknown>;
  copyProjectToVolume: (projectId: string) => Promise<unknown>;
  selectFolder: (defaultPath?: string) => Promise<unknown>;
  detectLaravel: (folderPath: string) => Promise<unknown>;
  devcontainerExists: (folderPath: string) => Promise<unknown>;
  getContainerStatus: (projectId: string) => Promise<{ running: boolean; exists: boolean }>;
  onCopyProgress: (callback: (projectId: string, progress: unknown) => void) => () => void;
}

interface ShellContext {
  openFolder: (projectId: string) => Promise<{ success: boolean; error?: string }>;
  openBrowser: (projectId: string) => Promise<{ success: boolean; error?: string }>;
  openEditor: (
    projectId: string,
    settings?: { defaultEditor: string; defaultTerminal: string }
  ) => Promise<{ success: boolean; error?: string }>;
  openTerminal: (
    projectId: string,
    settings?: { defaultEditor: string; defaultTerminal: string }
  ) => Promise<{ success: boolean; error?: string }>;
  openTinker: (
    projectId: string,
    settings?: { defaultEditor: string; defaultTerminal: string }
  ) => Promise<{ success: boolean; error?: string }>;
}

interface LogLine {
  projectId: string;
  line: string;
  stream: 'stdout' | 'stderr';
  timestamp: number;
}

interface ProjectLogsContext {
  start: (projectId: string) => Promise<{ success: boolean; error?: string }>;
  stop: (projectId: string) => Promise<void>;
  onLine: (callback: (log: LogLine) => void) => () => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  docker: DockerContext;
  services: ServicesContext;
  projects: ProjectsContext;
  shell: ShellContext;
  projectLogs: ProjectLogsContext;
}
