// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<'dark' | 'light' | 'system'>;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface DockerContext {
  getStatus: () => Promise<{ isRunning: boolean; error?: string }>;
  getNetworkName: () => Promise<string>;
  ensureNetwork: () => Promise<void>;
  connectToNetwork: (containerIdOrName: string) => Promise<void>;
  disconnectFromNetwork: (containerIdOrName: string) => Promise<void>;
}

interface ServicesContext {
  getAllServices: () => Promise<unknown>;
  getService: (serviceId: string) => Promise<unknown>;
  installService: (serviceId: string, options?: unknown) => Promise<unknown>;
  uninstallService: (serviceId: string, removeVolumes?: boolean) => Promise<unknown>;
  startService: (serviceId: string) => Promise<unknown>;
  stopService: (serviceId: string) => Promise<unknown>;
  restartService: (serviceId: string) => Promise<unknown>;
  updateConfig: (serviceId: string, customConfig: unknown) => Promise<unknown>;
  onInstallProgress: (callback: (serviceId: string, progress: unknown) => void) => () => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  docker: DockerContext;
  services: ServicesContext;
}
